### PR TITLE
app icons

### PR DESCRIPTION
**Pull request by aftabkhalid**
Closes: #149 

1024x1024-android

1024x1024-ios

### CODE REVIEW

**Comment by artalat** [comment]
Please add source files as well

**Comment by artalat** [comment]
can you remove extra whitespace and crop android icon and logo images

**Comment by aftabkhalid** [comment]
Sir please review splash screen for BlueBase

splash

**Comment by artalat** [comment]
@aftabkhalid can you please make the following changes so we can merge this:

- crop extra white space from bluebase icon
- need to see new options for splash screen
- create loading animation for web 

cc: @ammarkhan967

**Comment by ammarkhan967** [comment]
@aftabkhalid can you please upload the 

> @aftabkhalid can you please make the following changes so we can merge this:
> 
> * crop extra white space from bluebase icon
> * need to see new options for splash screen
> * create loading animation for web
> 
> cc: @ammarkhan967


@aftabkhalid can you please upload the splash screen after the required changes ????

**Comment by aftabkhalid** [comment]
Splash screen pushed to "bluebase/app-icons"

splash

also icons has been cropped, please check it out and let me know if there is any problem,

Thanks

**Comment by artalat** [comment]
when can we close this? need loading gif.

loading

**Comment by ammarkhan967** [comment]
> when can we close this? need loading gif.
> 
> loading

**Comment by aftabkhalid** [comment]
Sir please review the logos and let me know if you feel any problem.

bluebase-electron
bluebase-expo
bluebase-storybook
bluebase-storybook-native
bluebase-web

**Comment by artalat** [comment]
@ammarkhan967 can you have cli images pushed to the cli repo?

**Comment by artalat** [comment]
@ammarkhan967 when can we close this

**Pull request merged**
