### PR TITLE
chore(Package): Update Package

### PR DESCRIPTION
**Pull request by ammarkhan967**

### CODE REVIEW

**Comment by ammarkhan967** [comment]
@artalat not authorized to push directly into master that's why made this branch after updating the package

**Comment by ammarkhan967** [comment]
@hashim-sohail can you please look into this package ??? github worklfow npmrc registry path is incorrect

**Comment by hashim-sohail** [comment]
> @hashim-sohail can you please look into this package ??? github worklfow npmrc registry path is incorrect

Fixed. NPMRC file is not required in this package

**Pull request merged**
